### ISSUE TITLE
Question : Observer is not working on second time for much data

### ISSUE THREAD

**Issue by beta1910** [stuffrabbit/iCoAP#1]
Hi 
I used this library in my project. I used observer which is working for very first time. But It is not working if  data is huge and for second call. 
Second observer only receive last packet in his call.
Please can you help me on this ?

Thanks in advance.

**Comment by stuffrabbit** [comment]
Hi,
thanks for using iCoAP.
Do you mean you do not receive observe messages properly if they are combined with the Block2 option? Please provide more information on what data you send and receive (and which options are involved).

Greetings

**Comment by beta1910** [comment]
Thanks for quick response,
I have added only IC_OBSERVE with URI_PATH. I got response for following
a- either i have small data (ex: json with two objects in array)
b- or use for very first time with huge data(ex: json with more than 10 array objects  )
On second time if data is huge (ex: json with more than 10 array objects ), it automatically start to use IC_CONTENT_FORMAT and finally it send me only last packet data.
My json changes frequently. and it gonna increase rapidly,

Finally for second time with huge data observer does not give all packets. 

Thanks

**Comment by stuffrabbit** [comment]
To make sure I understand: You are observing a resource, which notifies you with JSON arrays and each observe notifications always contains the entire array? Or are you combining the data from all notifications to build up an array (this is not recommendable)?

However, you have to keep in mind that an observe-message reordering is performed by iCoAP (and any other CoAP client which conforms to RFC 7252), meaning that only the lastest observe notification is delivered to the delegate implementing the ICoAPExchange., i.e. if your notifications arrive out of order you won't receive all packages, as "older" notifications are filtered out automatically (this is the purpose of observe).
