### ISSUE TITLE
Issue in setting BLOCK1 data.

### ISSUE THREAD

**Issue by ShailendraGangwar** [stuffrabbit/iCoAP#10]
I am unable to set BLOCK1 option.

On adding option IC_BLOCK1, server gives below error.

INFO: Block1 transfer timed out: CON-PUT    MID= 1076, Token=, OptionSet={"Uri-Path":["15001","7"], "Block1":"(szx=0/16, m=false, num=787)"}, "{"9001":"123456789012345".. 64 bytes

Can you please tell, how to add option for BLOCK1?

**Comment by stuffrabbit** [comment]
Hey,
the Block1 option is currently not supported. Please feel free to contribute!
