### ISSUE TITLE
How to configure security code / key from the ikea tradfri gateway ?

### ISSUE THREAD

**Issue by ticatagdev** [stuffrabbit/iCoAP#11]
How to configure security code / key from the ikea tradfri gateway ?

**Comment by ticatagdev** [comment]
I would like to connect to the Tradfri IKEA gateway.
DTLS support with PSK is required.
Can you please advice or update library to take this feature into account ?

**Comment by stuffrabbit** [comment]
Hey DTLS is not supported in this library. Please feel free to fork and contribute this feature.
