### ISSUE TITLE
Question: Support for DTLS?

### ISSUE THREAD

**Issue by billybobbain** [stuffrabbit/iCoAP#3]
Do you have any plans to support DTLS?

**Comment by stuffrabbit** [comment]
Hi, 
as I'm currently working on another CoAP Implementation (SwiftCoAP- More functionality than iCoAP - Check it out here: https://github.com/stuffrabbit/SwiftCoAP) and other projects, I honestly said do not have much time left and therefore do not intend (for now) to add any significant updates for iCoAP. 
Maybe someday :)

**Comment by LRSEngineering** [comment]
We're not ready to move to Swift just yet. Is there an example of using BLOCK2 with iCoAP?

**Comment by stuffrabbit** [comment]
Hi,
Block2 is automatically handled by iCoAP, i.e. in case a response to your request sent by iCoAP contains a Block2 option, iCoAP will  automatically request the remaining blocks in successive order. There is nothing you must to. 

You can try it out by requesting the resource *large* from coap.me:5683 (e.g. with the example project).

**Comment by LRSEngineering** [comment]
Wow, it really was that easy. My test was closing the exchange. Once I stopped doing that it worked like a charm. Thanks!

**Comment by stuffrabbit** [comment]
You're welcome :)
