### ISSUE TITLE
DTLS support

### ISSUE THREAD

**Issue by beta1910** [stuffrabbit/iCoAP#4]
Hi
First thank you very much for nice implementation in this library. 

I am using this library in my project and now i need to give DTLS support. Any idea how can i implement DTLS or any plan you have for implementing for DTLS in recent future. You can also help me for getting some approach so i can look into this.

Thank you very much.
:)

**Comment by stuffrabbit** [comment]
Hi,
due to my involvement in other projects I won't be able to implement this feature in the near future. Sorry for that..

Kind regards 

Wojtek
