### ISSUE TITLE
[iOS]Socket close automatically when application goes in background.

### ISSUE THREAD

**Issue by beta1910** [stuffrabbit/iCoAP#5]
Hi stuffrabbit

I am facing weird problem in iOS. I was successfully able to start communication to server through library. But whenever application goes in background, all socket close automatically. On high level it cancels all observers.

Can you please help me on this.

Thanks
KD

**Comment by stuffrabbit** [comment]
Hi beta1910,
iOS automatically closes udp sockets when the app remains in the background for a while. You have to setup the sockets if necessary whenever the app enters the foreground again. Additionally, you cannot continue observing resources when the app is in the background.

Greetings
Wojtek
